### ISSUE TITLE
Open Source push - Agenda (7/27 and 7/30)

### ISSUE THREAD

**Issue by ivanov** [jupyter/colaboratory#8]
put agenda here:
- [x] setup colaboratory.jupyter.org to use as an entry point for the webapp. Validate that someone other than @fperez can do it with the common dreamhost credentials. See #20.
- [x] review history of the current repo and see whether we need to filter big binaries out of it first. See #26.
- [x] test install instructions/readme on a clean machine for accuracy. See #46.
- [x] list any current deviations of file format and sketch out future plans for each.
- [x] include in README a clear explanation of the differences in experience/capabilities between this and a 'regular' ipython install.
- [x] upgrade coLaboratory to v2
- [x] create plan for adding collaborative functionality within core IPython
- [x] Remove modified IPython source code from repo and figure out a better way of doing that
